version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:80"  # Expose the app on port 8000 of the host
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=mydatabase;Username=postgres;Password=mysecretpassword

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"  # Maps port 5432 inside the container to port 5432 on the host
    volumes:
      - pgdata:/var/lib/postgresql/data  # Persist database data across container recreations

volumes:
  pgdata:
